In [178]:
import pandas as pd
df = pd.read_csv("C:\\Users\\isanchezjimene\\Documents\\TraderesCode\\toolbox-amiris-emlab\\scripts\\AMIRIS_combined.csv", sep=',')

# Conventional operator

In [179]:
filtered = df[df['variable'].isin(["CostsInEUR","ReceivedMoneyInEUR"])]
agents = filtered.AgentId.unique()
filtered.set_index("AgentId", "variable")

C:\Programs\Anaconda3\envs\spinetoolbox\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

                       ObjectClass            variable         value
AgentId
501      ConventionalPlantOperator          CostsInEUR  5.820340e+07
503      ConventionalPlantOperator          CostsInEUR  2.905261e+08
504      ConventionalPlantOperator          CostsInEUR  5.693393e+05
505      ConventionalPlantOperator          CostsInEUR  0.000000e+00
501      ConventionalPlantOperator  ReceivedMoneyInEUR  7.647664e+07
503      ConventionalPlantOperator  ReceivedMoneyInEUR  3.723620e+08
504      ConventionalPlantOperator  ReceivedMoneyInEUR  6.519933e+05
505      ConventionalPlantOperator  ReceivedMoneyInEUR  0.000000e+00
10       VariableRenewableOperator          CostsInEUR  0.000000e+00
20       VariableRenewableOperator          CostsInEUR  0.000000e+00
50       VariableRenewableOperator          CostsInEUR  0.000000e+00
51       VariableRenewableOperator          CostsInEUR  0.000000e+00
52       VariableRenewableOperator          CostsInEUR  0.000000e+00
53       VariableRenewableOperator          CostsInEUR  1.280687e+06
10       VariableRenewableOperator  ReceivedMoneyInEUR  1.026501e+08
20       VariableRenewableOperator  ReceivedMoneyInEUR  6.468664e+08
50       VariableRenewableOperator  ReceivedMoneyInEUR  1.053646e+09
51       VariableRenewableOperator  ReceivedMoneyInEUR  3.132360e+08
52       VariableRenewableOperator  ReceivedMoneyInEUR  8.848934e+07
53       VariableRenewableOperator  ReceivedMoneyInEUR  4.258554e+07

In [180]:
profits = []

In [181]:
#conventional and renewable profits
for agent in agents:
    revenue = filtered.loc[(filtered['variable'] == 'ReceivedMoneyInEUR') & (filtered['AgentId'] == agent)].value.item()
    costs   = filtered.loc[(filtered['variable'] == 'CostsInEUR') & (filtered['AgentId'] == agent)].value.item()
    profits.append([agent,(revenue - costs)])

In [182]:
# batteries
profitbatteries  = df.loc[df['variable'] == 'Profit']
agents = profitbatteries.AgentId.unique()
for agent in agents:
    profits.append([agent, profitbatteries.loc[(profitbatteries['AgentId'] == agent)].value.item()])

In [183]:
#highest profits
dfprofits = pd.DataFrame(profits, columns=["Agent", "profit"])
dfprofits.sort_values(by=['profit'], ascending=False)

    Agent        profit
6      50  1.053646e+09
5      20  6.468664e+08
7      51  3.132360e+08
4      10  1.026501e+08
8      52  8.848934e+07
1     503  8.183587e+07
9      53  4.130485e+07
0     501  1.827324e+07
10      7  1.638481e+07
2     504  8.265401e+04
3     505  0.000000e+00

In [198]:
HighestProfitAgent = dfprofits.iloc[0].Agent
BestInvestment = df.loc[(df['AgentId'] == HighestProfitAgent)]